version: 0.0
os: linux
files:
  - rm: /var/www/html/index.html
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: stop.bash
      timeout: 300
      runas: root
  AfterInstall:
    - location: start.bash
      timeout: 200
      runas: root
